// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	getpocket "github.com/whitekid/getpocket"
)

// ModifyRequester is an autogenerated mock type for the ModifyRequester type
type ModifyRequester struct {
	mock.Mock
}

// Delete provides a mock function with given fields: itemID
func (_m *ModifyRequester) Delete(itemID string) getpocket.ModifyRequester {
	ret := _m.Called(itemID)

	var r0 getpocket.ModifyRequester
	if rf, ok := ret.Get(0).(func(string) getpocket.ModifyRequester); ok {
		r0 = rf(itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(getpocket.ModifyRequester)
		}
	}

	return r0
}

// Do provides a mock function with given fields: ctx
func (_m *ModifyRequester) Do(ctx context.Context) (*getpocket.ModifyResponse, error) {
	ret := _m.Called(ctx)

	var r0 *getpocket.ModifyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*getpocket.ModifyResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *getpocket.ModifyResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*getpocket.ModifyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Favorite provides a mock function with given fields: itemID
func (_m *ModifyRequester) Favorite(itemID string) getpocket.ModifyRequester {
	ret := _m.Called(itemID)

	var r0 getpocket.ModifyRequester
	if rf, ok := ret.Get(0).(func(string) getpocket.ModifyRequester); ok {
		r0 = rf(itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(getpocket.ModifyRequester)
		}
	}

	return r0
}

type mockConstructorTestingTNewModifyRequester interface {
	mock.TestingT
	Cleanup(func())
}

// NewModifyRequester creates a new instance of ModifyRequester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewModifyRequester(t mockConstructorTestingTNewModifyRequester) *ModifyRequester {
	mock := &ModifyRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
